### ISSUE TITLE
Clarify the domain or class restriction associated to usedGoods and usedPackage

### ISSUE THREAD

**Issue by ocorcho** [silenroc1/FEDeRATED-copy#7]
In the ontology module of Business Service (specifically in line https://github.com/silenroc1/FEDeRATED-copy/blob/8b97c03171f3f6a75cb511156173c3a0a595cd95/BusinessService.ttl#L72 ) we can see that there is a class restriction for the class Consignment that identifies that for the property usedGoods is applicable to Consignment

However, the property usedGoods has its domain defined as LogisticsService, instead of BusinessTransation, which is what a Consignment is.

Therefore, either the domain should be made wider, or the class restriction is wrong. Our intuition is that the problem is in the domain associated to the property usedGoods.

Something similar happens with usedPackage.

**Comment by GiuliaBiagioni** [comment]
The domains respectively associated to the properties usedGoods, usedPackage have been removed. On a general level, the restrictions in the class consignment have been recently double checked by our team and fixed in their conflicting aspects. The changes will be visible after the next update.

**Comment by ocorcho** [comment]
Checked, and ok with the resulting change.
